/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dasha Klyusova (https://sketchfab.com/AnoFail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hollow-knight-5a76d93e39984f829abd6f406562265b
Title: Hollow Knight
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HollowKnight = props => {
  const { nodes, materials } = useGLTF('/models/hollow-knight.glb')
  return (
    <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['null']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials['None.001']}
        />
    </group>
  )
}

useGLTF.preload('/models/hollow-knight.glb');

export default HollowKnight
